# Generated by Django 5.1.3 on 2024-11-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('hr', 'Hr')], max_length=10)),
                ('table_name', models.CharField(max_length=100)),
                ('allowed_fields', models.JSONField(default=list)),
                ('full_table_access', models.BooleanField(default=False)),
            ],
        ),
    ]
