# Generated by Django 5.1.3 on 2024-11-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_options_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='transaction_id',
        ),
    ]
