# Generated by Django 5.0.9 on 2024-12-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_deleted_at_customuser_deleted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
