# Generated by Django 5.0.9 on 2024-12-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_profile_profiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='People',
        ),
    ]
