# Generated by Django 5.0.9 on 2024-12-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_profiles_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
